server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/c0f
    username: c0f
    password: c0f
jwt:
  secret: my-super-secret-key-minimum-32-bytes!!!
  expiration: 3600000 # 1 jam